name: mkdocs-release

on:
  push:
    branches: [ branch-* ]

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: set major/minor/bugfix release version
        working-directory: ./java
        run: echo "RELEASE_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | grep -Ev 'Download|INFO|WARNING')" >> $GITHUB_ENV

      - name: set major/minor release version
        run: echo "MAJOR_VERSION=$(echo $RELEASE_VERSION | sed 's/^\([0-9]*\.[0-9]*\).*$/\1/')" >> $GITHUB_ENV

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: install deps
        working-directory: ./python
        run: cp ../README.md . && pip3 install pip==22.0.3 && pip3 install -e .[python,dev,docs]

      - name: use dev mike
        run: pip3 uninstall -y mike && pip3 install git+'https://github.com/jimporter/mike.git'  

      - name: generate autodoc
        run: python3 auto_doc.py

      - name: setup git
        run: |
          git config --global user.name Mike
          git config --global user.email mike@docs.hopsworks.ai
      - name: mike deploy docs
        run: |
          mike deploy ${{ env.RELEASE_VERSION }} ${{ env.MAJOR_VERSION }} -u --push
          mike alias ${{ env.RELEASE_VERSION }} latest -u --push
